
project_id = "lusfthgqlkgktplplqnv"

[auth.external.google]
enabled = true
client_id = "50578184076-p1lcvpjklhc4i16r02cp0jp16i3i2ds8.apps.googleusercontent.com"
secret = "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"
