
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lusfthgqlkgktplplqnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1c2Z0aGdxbGtna3RwbHBscW52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTg2ODAsImV4cCI6MjA2MTczNDY4MH0.rGF7pOjYLtFNK9sOG2MXH8M5wBOMG18w3F1YMoVUQoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Using Database type to ensure type safety
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});

// Extend the supabase client with table-specific typed methods for better DX
export const tables = {
  profiles: () => supabase.from('profiles'),
  products: () => supabase.from('products'),
  quote_requests: () => supabase.from('quote_requests'),
}

// Update the QuoteRequest interface to include admin_response
export interface QuoteRequest {
  id: string;
  created_at: string;
  product_id?: string | null;
  user_id: string;
  status?: string | null;
  product_name: string;
  quantity: string;
  unit: string;
  additional_details?: string | null;
  name: string;
  email: string;
  phone: string;
  company?: string | null;
  admin_response?: string | null;
}

// Google OAuth provider is already implemented in useAuth.tsx
